site:
  title: Jmix and Firebird
  start_page: jmix-firebird:firebird:overview.adoc
content:
  sources:
    - url: https://github.com/makssent/jmix-firebird-tutorial.git
      branches: release_firebird_3.0
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
