= Подключение Firebird к Jmix-проекту

Firebird поддерживается в Jmix через аддон https://www.jmix.ru/marketplace/firebird-db/[Firebird в Jmix Marketplace^]. Для подключения Firebird к приложению добавьте аддон и настройте подключение к базе данных.

[IMPORTANT]
====
Этот раздел рассчитан прежде всего на перенос готового Jmix-приложения на Firebird. Если приложения ещё нет, то можно взять за основу https://github.com/makssent/jmix-firebird-application[jmix-firebird-application^] — минимальный Jmix-проект из стандартного шаблона, уже настроенный для Firebird.

Если же нет опыта работы с Jmix, лучше начать с xref:tutorial:index.adoc[самоучителя] в котором отражена работа с Jmix + Firebird.
====

Интеграция проверена на реальном приложении https://github.com/makssent/jmix-crm-firebird[jmix-crm-firebird^]: приложение удалось запустить и использовать с Firebird, Liquibase создавал схему, тесты подключались через Jaybird, а основной функционал проекта работал, что отражено в разделе xref:migration.adoc[].
Для настройки потребуются:

* запущенный сервер Firebird 4.0+;
* пустая база данных (базу нужно создать до первого запуска приложения);
* учетная запись с правами на создание и изменение объектов базы данных.

[[configuration]]
== Настройка подключения

[[dependencies]]
[[datasource]]
=== Зависимости и application.properties

В блок `dependencies` файла `build.gradle` Jmix-проекта нужно добавить стартер аддона и драйвер Jaybird:

[source,groovy,subs="attributes+"]
----
dependencies {
    implementation '{addon-group}:jmix-firebird-starter:{addon-version}'
    runtimeOnly 'org.firebirdsql.jdbc:jaybird:{jaybird-version}'
}
----

[IMPORTANT]
====
Аддон jmix-firebird версии `{addon-version}` адаптирован для работы только с Jmix {latest-version}.
====

После изменения файла Gradle-проект нужно обновить в IDE.

В `src/main/resources/application.properties` нужно заменить стандартные параметры источника данных на параметры подготовленной базы Firebird, а затем добавить свойства драйвера и типа СУБД:

[source,properties]
----
main.datasource.url=jdbc:firebird://localhost:3050//path/to/application.fdb?encoding=UTF8
main.datasource.username=sysdba
main.datasource.password=your_password

# Добавлено для Firebird
main.datasource.driver-class-name=org.firebirdsql.jdbc.FBDriver
jmix.data.dbms-type=firebird
----

В JDBC URL значение `/path/to/application.fdb` нужно заменить на путь к файлу базы данных Firebird, а `sysdba` и `your_password` — на имя пользователя и пароль базы.

Firebird отсутствует в стандартном наборе типов СУБД, по которому Jmix определяет базу автоматически. Поэтому свойство `jmix.data.dbms-type=firebird` явно сообщает Jmix, что основной источник данных работает с Firebird. По этому значению Jmix использует Firebird-реализации, зарегистрированные аддоном.

Пример подключения зависимостей и настройки `application.properties` можно посмотреть в https://github.com/makssent/jmix-crm-firebird/commit/48d1c6e2c58bdbdcf6eb9468c36f54f73f0eeedb[коммите проекта jmix-crm-firebird^].

[[liquibase]]
=== Изменение Liquibase changelog-ов

В файл `changelog.xml` нужно добавить включение changelog аддона и разместить его перед уже существующими включениями модулей Jmix и changelog-ов приложения:

[source,xml]
----
<include file="/io/github/makssent/jmix/firebird/liquibase/changelog.xml"/>
----

Порядок включений важен: changelog аддона объявляет значения свойств Liquibase для Firebird, которые используют следующие за ним скрипты.

В init-файлах Liquibase тип `UUID` нужно заменить на свойство `${uuid.type}` во всех UUID-колонках:

[source,xml]
----
<column name="ID" type="${uuid.type}">
----

Значение свойства `uuid.type` для Firebird задаётся подключённым changelog аддона.

В changelog-и приложения нужно добавить `firebird` в атрибуты `dbms`:

[source,xml]
----
<insert tableName="USER_" dbms="postgresql, mssql, hsqldb, firebird">
----

Пример изменений Liquibase для поддержки Firebird можно посмотреть в https://github.com/makssent/jmix-crm-firebird/commit/213b0b3717eced383e9fefa3d0b5b4e2fcf22ff9[коммите проекта jmix-crm-firebird^].

Порядок ручного создания новых changelog-ов описан в разделе xref:liquibase-changelog.adoc[Создание Liquibase changelog].

Известные ограничения интеграции собраны в разделе xref:limitations.adoc[Ограничения Firebird]. Практический путь адаптации готового приложения показан в разделе xref:migration.adoc[Пример переноса приложения на Firebird].

== Заключение

После выполнения этих шагов Jmix-приложение может работать с Firebird. Могут возникнуть отдельные проблемы совместимости из-за особенностей Firebird или его поддержки в сторонних библиотеках, например xref:limitations.adoc#sequence-start-value[ограничение `startValue` для sequence], но данные проблемы не препятствуют интеграции в целом: до исправления соответствующей библиотеки для них можно применять локальные обходные решения.
